### ISSUE TITLE
Amazing fork !! add transparency hotkey (from another fork)

### ISSUE THREAD

**Issue by ncoquelet** [Ashod/Console2#1]
Hi, You make my day !!!!!

Your fork is amazing, specialy the fix for the hidden current line problem.

Here a feature idea from an other unofficial fork.
- Hotkey to change or toggle the transparency !

https://github.com/jonwingfield/Console2/

I love to see a merge of your two forks !!

Regards

**Comment by Ashod** [comment]
Thanks.

I believe the hotkey change is already merged. Try it out and let me know if it doesn't work.

**Comment by ncoquelet** [comment]
I'm not so curious :-)

It works like a charm !!!

You need more stars  :-D

**Comment by Ashod** [comment]
Happy you found it useful. Let me know if you have requests/suggestions to improve further.
